apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.5.0-beta.0
        args:
        - -config.file=/etc/alertmanager/config.yml
        - -storage.path=/alertmanager
        ports:
        - name: webui
          containerPort: 9093
          hostPort: 9093
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 2500Mi
        volumeMounts:
        - mountPath: /alertmanager
          name: data
        - mountPath: /etc/alertmanager
          name: config-volume
      volumes:
      - emptyDir: {}
        name: data
      - configMap:
          name: alertmanager-config
        name: config-volume
