kind: LimitRange
apiVersion: v1
metadata:
  name: monitoring-limits
  namespace: monitoring
spec:
  limits:
  - type: Pod
    max:
      cpu: "3"
      memory: 3Gi
    min:
      cpu: 10m
      memory: 3Mi
  - type: Container
    default:
      cpu: 300m
      memory: 250Mi
    defaultRequest:
      cpu: 50m
      memory: 10Mi
    max:
      cpu: "3"
      memory: 3Gi
    min:
      cpu: 10m
      memory: 3Mi