apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: l5d
  name: l5d
spec:
  template:
    metadata:
      labels:
        app: l5d
    spec:
      containers:
      - name: l5d
        image: buoyantio/linkerd:0.8.1
        args:
        - "/io.buoyant/linkerd/config/config.yaml"
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: "l5d-config"
          mountPath: "/io.buoyant/linkerd/config"
          readOnly: true
        ports:
        - name: incoming
          hostPort: 4141
          containerPort: 4141
        - name: outgoing
          hostPort: 4140
          containerPort: 4140
        - name: admin
          hostPort: 9990
          containerPort: 9990
      - name: kubectl
        image: buoyantio/kubectl:v1.4.0
        args:
        - "proxy"
        - "-p"
        - "8001"
      volumes:
      - name: l5d-config
        configMap:
          name: "l5d-config"