kind: Service
apiVersion: v1
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - name: https
      port: 9090
      protocol: TCP
  selector:
    app: prometheus