apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v1.2.0
        args:
        - -config.file=/etc/prometheus/prometheus.yml
        - -alertmanager.url=http://alertmanager:9093
        - -storage.local.path=/prometheus
        - -storage.local.retention=24h
        ports:
        - name: webui
          hostPort: 9090
          containerPort: 9090
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 2500Mi
        volumeMounts:
        - mountPath: /prometheus
          name: data
        - mountPath: /etc/prometheus
          name: config-volume
      volumes:
      - name: data
        emptyDir: {}
      - name: config-volume
        configMap:
          name: prometheus-config
