kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
        kind: ui
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:3.1.0
          ports:
          - name: webui
            hostPort: 3000
            containerPort: 3000
          resources:
            requests:
              cpu: 250m
              memory: 300Mi
          env:
            - name: GF_AUTH_BASIC_ENABLED
              value: "false"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
            # - name: GF_SERVER_ROOT_URL
            #   value: /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/
          volumeMounts:
          - name: grafana-persistent-storage
            mountPath: /var
      volumes:
      - name: grafana-persistent-storage
        emptyDir: {}