kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kibana
  labels:
    app: fluentd-elasticsearch-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: gcr.io/google_containers/kibana:v4.6.1
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 550m
            memory: 2Gi
          requests:
            cpu: 450m
            memory: 1Gi
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://elasticsearch:9200"
          # - name: "KIBANA_BASE_URL"
          #   value: "/api/v1/proxy/namespaces/monitoring/services/kibana"
        ports:
        - name: ui
          hostPort: 5601
          containerPort: 5601
