kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: service-loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-loadbalancer
      version: v1
  template:
    metadata:
      labels:
        app: service-loadbalancer
        version: v1
    spec:
      nodeSelector:
        role: loadbalancer
      containers:
        - name: haproxy
          image: gcr.io/google_containers/servicelb:0.4
          volumeMounts:
          - mountPath: /var/run
            name: var-run
          ports:
          # for prometheus
          - containerPort: 9090
            hostPort: 9090
            protocol: TCP
          # for haproxy stats
          - containerPort: 1936
            hostPort: 1936
            protocol: TCP
          args:
          - "--tcp-services=prometheussvc:9090"