kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.1
          env:
            - name: MYSQL_USER
              value: "exporter"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "prometheus"
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          ports:
            - name: server
              containerPort: 3306
        - name: mysql-exporter
          image: prom/mysqld-exporter:master
          env:
            - name: DATA_SOURCE_NAME
              value: "exporter:password@(localhost:3306)/prometheus"
          ports:
          - name: exporter
            containerPort: 9104
      volumes:
        - name: data
          emptyDir: {}