kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: node-exporter
spec:
  template:
    metadata:
      name: node-exporter
      labels:
        app: node-exporter
    spec:
      hostPID: true
      containers:
      - name: node-exporter
        # image: prom/node-exporter:0.12.0
        # image: prom/node-exporter:v0.13.0-rc.1
        image: weaveworks/node_exporter:master-abe8e29
        ports:
        - name: exporter
          # hostPort: 9100
          containerPort: 9100
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 25m
            memory: 20Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
      volumes:
      - name: rootfs
        hostPath:
          path: /
