kind: Service
apiVersion: v1
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: node-exporter
  name: node-exporter
spec:
  type: NodePort
  selector:
    app: node-exporter
  ports:
  - name: exporter
    port: 9100
