kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: weavescope-probe
  labels:
    app: weavescope
    weavescope-component: weavescope-probe
spec:
  template:
    metadata:
      name: weavescope-probe
      labels:
        app: weavescope
        weavescope-component: weavescope-probe
    spec:
      hostPID: true
      hostNetwork: true
      containers:
        - name: weavescope-probe
          image: 'weaveworks/scope:0.17.1'
          args:
            - '--no-app'
            - '--probe.docker.bridge=docker0'
            - '--probe.docker=true'
            - '--probe.kubernetes=true'
            - '$(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)'
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 50m
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: scope-plugins
              mountPath: /var/run/scope/plugins
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: scope-plugins
          hostPath:
            path: /var/run/scope/plugins