apiVersion: v1
kind: ReplicationController
metadata:
  name: linkerd-viz
  labels:
    name: linkerd-viz
spec:
  replicas: 1
  selector:
    name: linkerd-viz
  template:
    metadata:
      labels:
        name: linkerd-viz
    spec:
      containers:
      - name: linkerd-viz
        image: buoyantio/linkerd-viz:latest
        args: ["k8s"]
        imagePullPolicy: Always
        env:
        - name: PUBLIC_PORT
          value: "3000"
        - name: STATS_PORT
          value: "9090"
        ports:
        - name: grafana
          containerPort: 3000
        - name: prometheus
          containerPort: 9090
      - name: kubectl
        image: buoyantio/kubectl:v1.4.0
        args:
        - "proxy"
        - "-p"
        - "8001"