apiVersion: v1
kind: Service
metadata:
  name: linkerd-viz
  labels:
    name: linkerd-viz
spec:
  type: NodePort
  ports:
  - name: grafana
    port: 80
    targetPort: 3000
  - name: prometheus
    port: 9090
    targetPort: 9090
  selector:
    name: linkerd-viz