apiVersion: v1
kind: ReplicationController
metadata:
  name: hello
spec:
  replicas: 3
  selector:
    app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: service
        image: buoyantio/helloworld:0.0.1
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
        - "/bin/bash"
        - "-c"
        - "HTTP_PROXY=`./hostIP.sh`:4140 python hello.py"
        ports:
        - name: service
          containerPort: 7777
      - name: kubectl
        image: buoyantio/kubectl:v1.4.0
        args:
        - proxy
        - "-p"
        - "8001"